services:
  - type: web
    name: NER-app
    runtime: docker
    autoDeploy: false
    plan: free
    buildCommand: pip install -r requirements.txt
    dockerCommand: uvicorn src.api.app:app --host 0.0.0.0 --port $PORT

